// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG2YrAFxR-FFVgtB41bKcSkIi8V4SoomA',
    appId: '1:433387828741:web:9feb38b7848050f6f80e6c',
    messagingSenderId: '433387828741',
    projectId: 'shiffters-cbbbb',
    authDomain: 'shiffters-cbbbb.firebaseapp.com',
    storageBucket: 'shiffters-cbbbb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZYvw_ngBHSKyQzA9TzLD1Fx8D4CDROVk',
    appId: '1:433387828741:android:f674f3b2fe92a70af80e6c',
    messagingSenderId: '433387828741',
    projectId: 'shiffters-cbbbb',
    storageBucket: 'shiffters-cbbbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXtCio6ZWWuS47Zr9hmveEV-6lfeP6tyA',
    appId: '1:433387828741:ios:e77a89057997941af80e6c',
    messagingSenderId: '433387828741',
    projectId: 'shiffters-cbbbb',
    storageBucket: 'shiffters-cbbbb.firebasestorage.app',
    iosBundleId: 'com.example.shiffters',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXtCio6ZWWuS47Zr9hmveEV-6lfeP6tyA',
    appId: '1:433387828741:ios:e77a89057997941af80e6c',
    messagingSenderId: '433387828741',
    projectId: 'shiffters-cbbbb',
    storageBucket: 'shiffters-cbbbb.firebasestorage.app',
    iosBundleId: 'com.example.shiffters',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG2YrAFxR-FFVgtB41bKcSkIi8V4SoomA',
    appId: '1:433387828741:web:9fbf57154e9a362ff80e6c',
    messagingSenderId: '433387828741',
    projectId: 'shiffters-cbbbb',
    authDomain: 'shiffters-cbbbb.firebaseapp.com',
    storageBucket: 'shiffters-cbbbb.firebasestorage.app',
  );

}